export enum ScrollPosition {
  TOP = 'top',
  BOTTOM = 'bottom',
}

export enum HTMLElements {
  BUTTON = 'button',
  TABLE = 'table',
  INPUT = 'input',
  DIV = 'div',
  SPAN = 'span',
  P = 'p',
  UL = 'ul',
  LI = 'li',
  A = 'a',
  FORM = 'form',
  LABEL = 'label',
  SELECT = 'select',
  OPTION = 'option',
  TEXTAREA = 'textarea',
  NAV = 'nav',
  HEADER = 'header',
  FOOTER = 'footer',
  MAIN = 'main',
  SECTION = 'section',
  ARTICLE = 'article',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
  HR = 'hr',
  IMG = 'img',
  IFRAME = 'iframe',
  OBJECT = 'object',
  EMBED = 'embed',
  VIDEO = 'video',
  AUDIO = 'audio',
  CANVAS = 'canvas',
  SVG = 'svg',
  BUTTON_GROUP = 'button-group',
  CARD = 'card',
  MODAL = 'modal',
  ALERT = 'alert',
  TOAST = 'toast',
  PROGRESS = 'progress',
  DIALOG = 'dialog',
}
