import { MockupCases } from '../mockup-types';
import {
  IOS_SAFARI_MAC_LIKE_17_4_MOBILE,
  UA_IOS_14_IPAD_SAFARI_14_TABLET,
  UA_IOS_14_IPHONE_SAFARI_14_MOBILE,
  UA_IOS_15_IPHONE_CRIOS_108_MOBILE,
  UA_IOS_15_IPHONE_SAFARI_15_MOBILE,
  UA_IOS_16_IPAD_CRIOS_120_TABLET,
  UA_IOS_16_IPAD_FXIOS_120_TABLET,
  UA_IOS_16_IPAD_SAFARI_16_TABLET,
  UA_IOS_16_IPHONE_CRIOS_120_MOBILE,
  UA_IOS_16_IPHONE_EDGIOS_121_MOBILE,
  UA_IOS_16_IPHONE_FXIOS_120_MOBILE,
  UA_IOS_16_IPHONE_SAFARI_16_MOBILE,
  UA_IOS_17_IPAD_BRAVE_1_66_TABLET,
  UA_IOS_17_IPAD_CRIOS_125_TABLET,
  UA_IOS_17_IPAD_EDGIOS_125_TABLET,
  UA_IOS_17_IPAD_FXIOS_125_TABLET,
  UA_IOS_17_IPAD_OPERA_43_TABLET,
  UA_IOS_17_IPAD_SAFARI_17_TABLET,
  UA_IOS_17_IPHONE_BRAVE_1_66_MOBILE,
  UA_IOS_17_IPHONE_CRIOS_125_MOBILE,
  UA_IOS_17_IPHONE_EDGIOS_125_MOBILE,
  UA_IOS_17_IPHONE_FXIOS_125_MOBILE,
  UA_IOS_17_IPHONE_OPERA_43_MOBILE,
  UA_IOS_17_IPHONE_SAFARI_17_MOBILE,
  UA_IOS_17_IPHONE_YANDEX_24_4_MOBILE,
  UA_IOS_APPLEBOT_MOBILE,
  UA_IOS_FACEBOOK_WEBVIEW,
  UA_IOS_TWITTER_WEBVIEW,
} from './ios-ua-mockups';

export const iosCases: MockupCases[] = [
  {
    testName: 'iOS 17 iPhone Safari 17.4',
    ua: UA_IOS_17_IPHONE_SAFARI_17_MOBILE,
    platformVersion: '17.4',
    browser: 'Safari',
    browserVersion: '17.4',
    deviceType: 'mobile',
    maxTouchPoints: 5,
    hardwareConcurrency: 6,
    deviceMemory: 6,
  },
  {
    testName: 'iOS 17 iPhone Chrome 125',
    ua: UA_IOS_17_IPHONE_CRIOS_125_MOBILE,
    platformVersion: '17.4',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'mobile',
    maxTouchPoints: 5,
    hardwareConcurrency: 6,
  },
  {
    testName: 'iOS 17 iPhone Firefox 125',
    ua: UA_IOS_17_IPHONE_FXIOS_125_MOBILE,
    platformVersion: '17.4',
    browser: 'Firefox',
    browserVersion: '125.0',
    deviceType: 'mobile',
    vendor: '',
  },
  {
    testName: 'iOS 17 iPhone Edge 125',
    ua: UA_IOS_17_IPHONE_EDGIOS_125_MOBILE,
    platformVersion: '17.4',
    browser: 'Edge',
    browserVersion: '125.0.0.0',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 17 iPhone Opera Touch 43',
    ua: UA_IOS_17_IPHONE_OPERA_43_MOBILE,
    platformVersion: '17.4',
    browser: 'Opera',
    browserVersion: '43.0.2254.137688',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 17 iPhone Brave 1.66',
    ua: UA_IOS_17_IPHONE_BRAVE_1_66_MOBILE,
    platformVersion: '17.4',
    browser: 'Brave',
    browserVersion: '1.66.2',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 17 iPhone Yandex 24.4',
    ua: UA_IOS_17_IPHONE_YANDEX_24_4_MOBILE,
    platformVersion: '17.4',
    browser: 'Yandex',
    browserVersion: '24.4.1.934',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 16 iPhone Safari 16.6',
    ua: UA_IOS_16_IPHONE_SAFARI_16_MOBILE,
    platformVersion: '16.6',
    browser: 'Safari',
    browserVersion: '16.6',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 16 iPhone Chrome 120',
    ua: UA_IOS_16_IPHONE_CRIOS_120_MOBILE,
    platformVersion: '16.6',
    browser: 'Chrome',
    browserVersion: '120.0.6099.209',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 16 iPhone Firefox 120',
    ua: UA_IOS_16_IPHONE_FXIOS_120_MOBILE,
    platformVersion: '16.6',
    browser: 'Firefox',
    browserVersion: '120.0',
    deviceType: 'mobile',
    vendor: '',
  },
  {
    testName: 'iOS 16 iPhone Edge 121',
    ua: UA_IOS_16_IPHONE_EDGIOS_121_MOBILE,
    platformVersion: '16.6',
    browser: 'Edge',
    browserVersion: '121.0.0.0',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 17 iPad Safari 17.4',
    ua: UA_IOS_17_IPAD_SAFARI_17_TABLET,
    platformVersion: '17.4',
    browser: 'Safari',
    browserVersion: '17.4',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    hardwareConcurrency: 8,
    deviceMemory: 8,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 17 iPad Chrome 125',
    ua: UA_IOS_17_IPAD_CRIOS_125_TABLET,
    platformVersion: '17.4',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 17 iPad Firefox 125',
    ua: UA_IOS_17_IPAD_FXIOS_125_TABLET,
    platformVersion: '17.4',
    browser: 'Firefox',
    browserVersion: '125.0',
    deviceType: 'tablet',
    vendor: '',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 17 iPad Edge 125',
    ua: UA_IOS_17_IPAD_EDGIOS_125_TABLET,
    platformVersion: '17.4',
    browser: 'Edge',
    browserVersion: '125.0.0.0',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 17 iPad Opera Touch 43',
    ua: UA_IOS_17_IPAD_OPERA_43_TABLET,
    platformVersion: '17.4',
    browser: 'Opera',
    browserVersion: '43.0.2254.137688',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 17 iPad Brave 1.66',
    ua: UA_IOS_17_IPAD_BRAVE_1_66_TABLET,
    platformVersion: '17.4',
    browser: 'Brave',
    browserVersion: '1.66.2',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 16 iPad Safari 16.6',
    ua: UA_IOS_16_IPAD_SAFARI_16_TABLET,
    platformVersion: '16.7',
    browser: 'Safari',
    browserVersion: '16.6',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 16 iPad Chrome 120',
    ua: UA_IOS_16_IPAD_CRIOS_120_TABLET,
    platformVersion: '16.7',
    browser: 'Chrome',
    browserVersion: '120.0.6099.118',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 16 iPad Firefox 120',
    ua: UA_IOS_16_IPAD_FXIOS_120_TABLET,
    platformVersion: '16.7',
    browser: 'Firefox',
    browserVersion: '120.0',
    deviceType: 'tablet',
    vendor: '',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS 15 iPhone Safari 15.6',
    ua: UA_IOS_15_IPHONE_SAFARI_15_MOBILE,
    platformVersion: '15.7.9',
    browser: 'Safari',
    browserVersion: '15.6',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 15 iPhone Chrome 108',
    ua: UA_IOS_15_IPHONE_CRIOS_108_MOBILE,
    platformVersion: '15.7.9',
    browser: 'Chrome',
    browserVersion: '108.0.5359.124',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 14 iPhone Safari 14.1',
    ua: UA_IOS_14_IPHONE_SAFARI_14_MOBILE,
    platformVersion: '14.8',
    browser: 'Safari',
    browserVersion: '14.1',
    deviceType: 'mobile',
  },
  {
    testName: 'iOS 14 iPad Safari 14.0',
    ua: UA_IOS_14_IPAD_SAFARI_14_TABLET,
    platformVersion: '14.8',
    browser: 'Safari',
    browserVersion: '14.0',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1024,
    height: 1366,
    pixelRatio: 2,
  },
  {
    testName: 'iOS Applebot crawler',
    ua: UA_IOS_APPLEBOT_MOBILE,
    platformVersion: '17.4',
    browser: 'Unknown',
    deviceType: 'bot',
    agentType: 'bot',
    vendor: '',
    maxTouchPoints: 0,
    hardwareConcurrency: 2,
    deviceMemory: 2,
  },
  {
    testName: 'iOS Facebook in-app browser',
    ua: UA_IOS_FACEBOOK_WEBVIEW,
    platformVersion: '17.4',
    browser: 'Unknown',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'iOS Twitter in-app browser',
    ua: UA_IOS_TWITTER_WEBVIEW,
    platformVersion: '17.4',
    browser: 'Unknown',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'iOS on moble Macintosh',
    ua: IOS_SAFARI_MAC_LIKE_17_4_MOBILE,
    platformVersion: '17.4',
    browser: 'Safari',
    browserVersion: '17.4',
    deviceType: 'tablet',
    maxTouchPoints: 5,
  },
];
