import { MockupCases } from '../mockup-types';
import {
  UA_MACOS_BRAVE_1_66_SONOMA,
  UA_MACOS_CHROME_109_CATALINA,
  UA_MACOS_CHROME_122_MONTEREY,
  UA_MACOS_CHROME_125_SONOMA_ARM64,
  UA_MACOS_CHROME_125_SONOMA_ARM64_TAIL,
  UA_MACOS_CHROME_125_SONOMA_X64,
  UA_MACOS_CHROME_125_SONOMA_X64_TAIL,
  UA_MACOS_EDGE_125_SONOMA,
  UA_MACOS_FIREFOX_115_CATALINA,
  UA_MACOS_FIREFOX_125_SONOMA,
  UA_MACOS_HEADLESS_CHROME_125,
  UA_MACOS_OPERA_108_SONOMA,
  UA_MACOS_SAFARI_13_HIGH_SIERRA,
  UA_MACOS_SAFARI_16_6_MONTEREY,
  UA_MACOS_SAFARI_17_4_SONOMA,
  UA_MACOS_VIVALDI_6_7_SONOMA,
  UA_MACOS_YANDEX_24_4_SONOMA,
} from './macos-ua-tests';

export const macOSCases: MockupCases[] = [
  {
    testName: 'Sonoma — Safari 17.4.1 → Safari/17.4.1, desktop',
    ua: UA_MACOS_SAFARI_17_4_SONOMA,
    platformVersion: '14.4.1',
    browser: 'Safari',
    browserVersion: '17.4.1',
    deviceType: 'desktop',
    vendor: 'Apple Computer, Inc.',
    maxTouchPoints: 0,
    hardwareConcurrency: 8,
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Chrome 125 (Intel token) → Chrome/125, desktop',
    ua: UA_MACOS_CHROME_125_SONOMA_X64,
    platformVersion: '14.4.1',
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    deviceType: 'desktop',
    hardwareConcurrency: 10,
    deviceMemory: 16,
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName:
      'Sonoma — Chrome 125 (ARM64 token) → Chrome/125, desktop, arm64/64',
    ua: UA_MACOS_CHROME_125_SONOMA_ARM64,
    platformVersion: '14.4.1',
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    deviceType: 'desktop',
    architecture: 'arm64',
    bitness: 64,
    hardwareConcurrency: 8,
    deviceMemory: 16,
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Edge 125 → Edge/125, desktop',
    ua: UA_MACOS_EDGE_125_SONOMA,
    platformVersion: '14.4.1',
    browser: 'Edge',
    browserVersion: '125.0.2535.79',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Firefox 125 → Firefox/125, desktop, vendor:""',
    ua: UA_MACOS_FIREFOX_125_SONOMA,
    platformVersion: '14.4',
    browser: 'Firefox',
    browserVersion: '125.0',
    deviceType: 'desktop',
    vendor: '',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Brave 1.66 → Brave/1.66, desktop',
    ua: UA_MACOS_BRAVE_1_66_SONOMA,
    platformVersion: '14.4.1',
    browser: 'Brave',
    browserVersion: '1.66.115',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Opera 108 → OPR/108, desktop',
    ua: UA_MACOS_OPERA_108_SONOMA,
    platformVersion: '14.4.1',
    browser: 'Opera',
    browserVersion: '108.0.5067.66',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Vivaldi 6.7 → Vivaldi/6.7, desktop',
    ua: UA_MACOS_VIVALDI_6_7_SONOMA,
    platformVersion: '14.4.1',
    browser: 'Vivaldi',
    browserVersion: '6.7.3329.41',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Yandex 24.4 → YaBrowser/24.4, desktop',
    ua: UA_MACOS_YANDEX_24_4_SONOMA,
    platformVersion: '14.4.1',
    browser: 'Yandex',
    browserVersion: '24.4.5.824',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Headless Chrome 125 → Chrome/125, desktop',
    ua: UA_MACOS_HEADLESS_CHROME_125,
    platformVersion: '14.4.1',
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Monterey — Safari 16.6 → Safari/16.6, desktop',
    ua: UA_MACOS_SAFARI_16_6_MONTEREY,
    platformVersion: '12.6',
    browser: 'Safari',
    browserVersion: '16.6',
    deviceType: 'desktop',
    vendor: 'Apple Computer, Inc.',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Monterey — Chrome 122 → Chrome/122, desktop',
    ua: UA_MACOS_CHROME_122_MONTEREY,
    platformVersion: '12.6',
    browser: 'Chrome',
    browserVersion: '122.0.6261.94',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Catalina — Chrome 109 → Chrome/109, desktop',
    ua: UA_MACOS_CHROME_109_CATALINA,
    platformVersion: '10.15.7',
    browser: 'Chrome',
    browserVersion: '109.0.5414.119',
    deviceType: 'desktop',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Catalina — Firefox 115 → Firefox/115, desktop, vendor:""',
    ua: UA_MACOS_FIREFOX_115_CATALINA,
    platformVersion: '10.15',
    browser: 'Firefox',
    browserVersion: '115.0',
    deviceType: 'desktop',
    vendor: '',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'High Sierra — Safari 13.1.2 → Safari/13.1.2, desktop',
    ua: UA_MACOS_SAFARI_13_HIGH_SIERRA,
    platformVersion: '10.13.6',
    browser: 'Safari',
    browserVersion: '13.1.2',
    deviceType: 'desktop',
    vendor: 'Apple Computer, Inc.',
    height: 800,
    orientation: 'landscape',
    pixelRatio: 2,
    width: 1440,
  },
  {
    testName: 'Sonoma — Chrome 125 (fallback arm64 from UA tail)',
    ua: UA_MACOS_CHROME_125_SONOMA_ARM64_TAIL,
    platformVersion: '14.4.1',
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    deviceType: 'desktop',
    architecture: 'arm64',
    bitness: 64,
    height: 800,
    width: 1440,
    pixelRatio: 2,
    orientation: 'landscape',
  },
  {
    testName: 'Sonoma — Chrome 125 (fallback x64 from UA tail)',
    ua: UA_MACOS_CHROME_125_SONOMA_X64_TAIL,
    platformVersion: '14.4.1',
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
    height: 800,
    width: 1440,
    pixelRatio: 2,
    orientation: 'landscape',
  },
];
