import { MockupCases } from '../mockup-types';
import {
  UA_LINUX_ALPINE_CHROMIUM_118_DESKTOP,
  UA_LINUX_ARCH_BRAVE_1_65_DESKTOP,
  UA_LINUX_ARCH_CHROME_125_DESKTOP,
  UA_LINUX_ARCH_CHROMIUM_122_DESKTOP,
  UA_LINUX_BINGBOT_DESKTOP,
  UA_LINUX_DEBIAN_CHROME_109_DESKTOP,
  UA_LINUX_DEBIAN_CHROMIUM_122_MIPS64_DESKTOP,
  UA_LINUX_DEBIAN_FIREFOX_115_DESKTOP,
  UA_LINUX_ELEMENTARY_FIREFOX_123_DESKTOP,
  UA_LINUX_FEDORA_CHROME_124_DESKTOP,
  UA_LINUX_FEDORA_CHROME_124_PPC64LE_DESKTOP,
  UA_LINUX_FEDORA_FIREFOX_123_DESKTOP,
  UA_LINUX_FEDORA_OPERA_108_DESKTOP,
  UA_LINUX_GOOGLEBOT_DESKTOP,
  UA_LINUX_HEADLESS_CHROME,
  UA_LINUX_MANJARO_FIREFOX_124_DESKTOP,
  UA_LINUX_MINT_CHROME_120_DESKTOP,
  UA_LINUX_MINT_VIVALDI_6_5_DESKTOP,
  UA_LINUX_POPOS_CHROME_125_DESKTOP,
  UA_LINUX_POPOS_FIREFOX_125_DESKTOP,
  UA_LINUX_PUPPY_CHROME_109_DESKTOP,
  UA_LINUX_UBUNTU_BRAVE_1_66_DESKTOP,
  UA_LINUX_UBUNTU_CHROME_125_DESKTOP,
  UA_LINUX_UBUNTU_EDGE_125_DESKTOP,
  UA_LINUX_UBUNTU_FIREFOX_125_DESKTOP,
  UA_LINUX_UBUNTU_OPERA_109_DESKTOP,
  UA_LINUX_UBUNTU_VIVALDI_6_7_DESKTOP,
  UA_LINUX_UBUNTU_YANDEX_24_4_DESKTOP,
} from './linux-ua-mockups';

export const LinuxCases: MockupCases[] = [
  {
    testName: 'Ubuntu Chrome 125 x86_64',
    ua: UA_LINUX_UBUNTU_CHROME_125_DESKTOP,
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    architecture: 'x64',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: 64,
    hardwareConcurrency: 12,
    deviceMemory: 16,
  },
  {
    testName: 'Ubuntu Firefox 125 x86_64',
    ua: UA_LINUX_UBUNTU_FIREFOX_125_DESKTOP,
    browser: 'Firefox',
    browserVersion: '125.0',
    architecture: 'x64',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: 64,
    vendor: '',
    hardwareConcurrency: 8,
  },
  {
    testName: 'Ubuntu Edge 125 x86_64',
    ua: UA_LINUX_UBUNTU_EDGE_125_DESKTOP,
    browser: 'Edge',
    browserVersion: '125.0.2535.79',
    architecture: 'x64',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: 64,
  },
  {
    testName: 'Ubuntu Opera 109 x86_64',
    ua: UA_LINUX_UBUNTU_OPERA_109_DESKTOP,
    browser: 'Opera',
    browserVersion: '109.0.5097.80',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Ubuntu Brave 1.66 x86_64',
    ua: UA_LINUX_UBUNTU_BRAVE_1_66_DESKTOP,
    browser: 'Brave',
    browserVersion: '1.66.115',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Ubuntu Vivaldi 6.7 x86_64',
    ua: UA_LINUX_UBUNTU_VIVALDI_6_7_DESKTOP,
    browser: 'Vivaldi',
    browserVersion: '6.7.3329.41',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Ubuntu Yandex 24.4 x86_64',
    ua: UA_LINUX_UBUNTU_YANDEX_24_4_DESKTOP,
    browser: 'Yandex',
    browserVersion: '24.4.5.824',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Fedora Chrome 124',
    ua: UA_LINUX_FEDORA_CHROME_124_DESKTOP,
    browser: 'Chrome',
    browserVersion: '124.0.6367.79',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Fedora Firefox 123',
    ua: UA_LINUX_FEDORA_FIREFOX_123_DESKTOP,
    browser: 'Firefox',
    browserVersion: '123.0',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
    vendor: '',
  },
  {
    testName: 'Fedora Opera 108',
    ua: UA_LINUX_FEDORA_OPERA_108_DESKTOP,
    browser: 'Opera',
    browserVersion: '108.0.5067.66',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Arch Chrome 125',
    ua: UA_LINUX_ARCH_CHROME_125_DESKTOP,
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Arch Chromium 122',
    ua: UA_LINUX_ARCH_CHROMIUM_122_DESKTOP,
    browser: 'Unknown',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Arch Brave 1.65',
    ua: UA_LINUX_ARCH_BRAVE_1_65_DESKTOP,
    browser: 'Brave',
    browserVersion: '1.65.132',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Manjaro Firefox 124',
    ua: UA_LINUX_MANJARO_FIREFOX_124_DESKTOP,
    browser: 'Firefox',
    browserVersion: '124.0',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
    vendor: '',
  },
  {
    testName: 'Debian Chrome 109 i686',
    ua: UA_LINUX_DEBIAN_CHROME_109_DESKTOP,
    browser: 'Chrome',
    browserVersion: '109.0.0.0',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x86',
    bitness: 32,
    hardwareConcurrency: 4,
    deviceMemory: 4,
  },
  {
    testName: 'Debian Firefox 115 i686',
    ua: UA_LINUX_DEBIAN_FIREFOX_115_DESKTOP,
    browser: 'Firefox',
    browserVersion: '115.0',
    architecture: 'x86',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: 32,
    vendor: '',
    hardwareConcurrency: 4,
    deviceMemory: 4,
  },
  {
    testName: 'Linux Mint Chrome 120',
    ua: UA_LINUX_MINT_CHROME_120_DESKTOP,
    browser: 'Chrome',
    browserVersion: '120.0.6099.199',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Linux Mint Vivaldi 6.5',
    ua: UA_LINUX_MINT_VIVALDI_6_5_DESKTOP,
    browser: 'Vivaldi',
    browserVersion: '6.5.3206.63',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'elementary OS Firefox 123',
    ua: UA_LINUX_ELEMENTARY_FIREFOX_123_DESKTOP,
    browser: 'Firefox',
    browserVersion: '123.0',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
    vendor: '',
  },
  {
    testName: 'Pop!_OS Chrome 125',
    ua: UA_LINUX_POPOS_CHROME_125_DESKTOP,
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
  },
  {
    testName: 'Pop!_OS Firefox 125',
    ua: UA_LINUX_POPOS_FIREFOX_125_DESKTOP,
    browser: 'Firefox',
    browserVersion: '125.0',
    platformVersion: undefined,
    deviceType: 'desktop',
    architecture: 'x64',
    bitness: 64,
    vendor: '',
  },
  {
    testName: 'Alpine Chromium 118',
    ua: UA_LINUX_ALPINE_CHROMIUM_118_DESKTOP,
    browser: 'Unknown',
    architecture: 'x64',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: 64,
  },
  {
    testName: 'Puppy Chrome 109 i686',
    ua: UA_LINUX_PUPPY_CHROME_109_DESKTOP,
    browser: 'Chrome',
    browserVersion: '109.0.0.0',
    architecture: 'x86',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: 32,
    hardwareConcurrency: 2,
    deviceMemory: 2,
  },
  {
    testName: 'Bots — Googlebot Linux desktop',
    ua: UA_LINUX_GOOGLEBOT_DESKTOP,
    browser: 'Unknown',
    architecture: undefined,
    bitness: undefined,
    agentType: 'bot',
    deviceType: 'bot',
    vendor: '',
    hardwareConcurrency: 4,
    deviceMemory: 4,
    platformVersion: undefined,
  },
  {
    testName: 'Bots — Bingbot Linux desktop',
    ua: UA_LINUX_BINGBOT_DESKTOP,
    browser: 'Unknown',
    architecture: undefined,
    bitness: undefined,
    agentType: 'bot',
    deviceType: 'bot',
    vendor: '',
    hardwareConcurrency: 2,
    deviceMemory: 2,
    platformVersion: undefined,
  },
  {
    testName: 'Tools — Headless Chrome on Linux',
    ua: UA_LINUX_HEADLESS_CHROME,
    browser: 'Chrome',
    browserVersion: '125.0.6422.76',
    architecture: 'x64',
    bitness: 64,
    platformVersion: undefined,
    deviceType: 'desktop',
  },
  {
    testName: 'Fedora Chrome 124 ppc64le',
    ua: UA_LINUX_FEDORA_CHROME_124_PPC64LE_DESKTOP,
    browser: 'Chrome',
    browserVersion: '124.0.6367.118',
    architecture: 'ppc', // <— ده اللي بيغطي فرع /ppc|powerpc/
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: undefined, // تسيبها undefined زي ما الدالة بترجّع
  },
  {
    testName: 'Debian Chromium 122 mips64',
    ua: UA_LINUX_DEBIAN_CHROMIUM_122_MIPS64_DESKTOP,
    browser: 'Unknown',
    browserVersion: undefined,
    architecture: 'mips',
    platformVersion: undefined,
    deviceType: 'desktop',
    bitness: undefined,
  },
];
