import { MockupCases } from '../mockup-types';
import {
  UA_ANDROID_10_PIXEL_CHROME_96_MOBILE,
  UA_ANDROID_10_PIXEL_FIREFOX_110_MOBILE,
  UA_ANDROID_11_ONEPLUS_EDGE_114_MOBILE,
  UA_ANDROID_11_OPERA_74_MOBILE,
  UA_ANDROID_11_PIXEL_CHROME_115_MOBILE,
  UA_ANDROID_11_PIXEL_FIREFOX_113_MOBILE,
  UA_ANDROID_11_SAMSUNG_SI_18_MOBILE,
  UA_ANDROID_12_GALAXY_TAB_S8_CHROME_120,
  UA_ANDROID_12_PIXEL_CHROME_120_MOBILE,
  UA_ANDROID_12_PIXEL_FIREFOX_119_MOBILE,
  UA_ANDROID_12_PIXEL_WEBVIEW_120,
  UA_ANDROID_12_SAMSUNG_SI_20_MOBILE,
  UA_ANDROID_12_XIAOMI_MIUI_CHROME_118_MOBILE,
  UA_ANDROID_13_OPPO_CHROME_124_MOBILE,
  UA_ANDROID_13_PIXEL_CHROME_123_MOBILE,
  UA_ANDROID_13_PIXEL_EDGE_124_MOBILE,
  UA_ANDROID_13_PIXEL_FOLD_CHROME_124,
  UA_ANDROID_13_PIXEL_FOLD_EDGE_124,
  UA_ANDROID_13_PIXEL_FIREFOX_124_MOBILE,
  UA_ANDROID_13_PIXEL_OPERA_78_MOBILE,
  UA_ANDROID_13_PIXEL_VIVALDI_6_7_MOBILE,
  UA_ANDROID_13_SAMSUNG_SI_23_MOBILE,
  UA_ANDROID_14_GALAXY_TAB_S9_SI_24,
  UA_ANDROID_14_ONEPLUS_BRAVE_1_66_MOBILE,
  UA_ANDROID_14_PIXEL_CHROME_125_MOBILE,
  UA_ANDROID_14_PIXEL_EDGE_125_MOBILE,
  UA_ANDROID_14_PIXEL_FIREFOX_125_MOBILE,
  UA_ANDROID_14_PIXEL_OPERA_79_MOBILE,
  UA_ANDROID_14_PIXEL_TABLET_CHROME_125,
  UA_ANDROID_14_PIXEL_TABLET_FIREFOX_125,
  UA_ANDROID_14_PIXEL_WEBVIEW_125,
  UA_ANDROID_14_PIXEL_YANDEX_24_4_MOBILE,
  UA_ANDROID_14_SAMSUNG_CHROME_125_MOBILE,
  UA_ANDROID_14_SAMSUNG_SI_24_MOBILE,
  UA_ANDROID_FACEBOOK_APP_WEBVIEW,
  UA_ANDROID_GOOGLEBOT_SMARTPHONE,
  UA_ANDROID_TWITTER_WEBVIEW,
  UA_ANDROID_8_HUAWEI_P20_CHROME_80_MOBILE,
  UA_ANDROID_9_GALAXY_S9_SI_17_MOBILE,
} from './android-ua-mockups';

export const androidCases: MockupCases[] = [
  {
    testName: 'Android 14 Pixel 8 Pro Chrome 125',
    ua: UA_ANDROID_14_PIXEL_CHROME_125_MOBILE,
    platformVersion: '14',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'mobile',
    maxTouchPoints: 5,
    hardwareConcurrency: 8,
    deviceMemory: 12,
    width: 412,
    height: 915,
    pixelRatio: 3,
  },
  {
    testName: 'Android 14 Pixel 8 Pro Firefox 125',
    ua: UA_ANDROID_14_PIXEL_FIREFOX_125_MOBILE,
    platformVersion: '14',
    browser: 'Firefox',
    browserVersion: '125.0',
    deviceType: 'mobile',
    vendor: '',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 Pixel 8 Edge 125',
    ua: UA_ANDROID_14_PIXEL_EDGE_125_MOBILE,
    platformVersion: '14',
    browser: 'Edge',
    browserVersion: '125.0.2535.78',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 Pixel 8 Pro Opera 79',
    ua: UA_ANDROID_14_PIXEL_OPERA_79_MOBILE,
    platformVersion: '14',
    browser: 'Opera',
    browserVersion: '79.4.4195.77163',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 Pixel 8 Pro Yandex 24.4',
    ua: UA_ANDROID_14_PIXEL_YANDEX_24_4_MOBILE,
    platformVersion: '14',
    browser: 'Yandex',
    browserVersion: '24.4.1.934',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 Galaxy S24 Samsung Internet 24',
    ua: UA_ANDROID_14_SAMSUNG_SI_24_MOBILE,
    platformVersion: '14',
    browser: 'Samsung Internet',
    browserVersion: '24.0',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 Galaxy S24 Chrome 125',
    ua: UA_ANDROID_14_SAMSUNG_CHROME_125_MOBILE,
    platformVersion: '14',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 OnePlus 12 Brave 1.66',
    ua: UA_ANDROID_14_ONEPLUS_BRAVE_1_66_MOBILE,
    platformVersion: '14',
    browser: 'Brave',
    browserVersion: '1.66.115',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 14 Pixel 8 Pro WebView Chrome 125',
    ua: UA_ANDROID_14_PIXEL_WEBVIEW_125,
    platformVersion: '14',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android 13 Pixel 7 Pro Chrome 123',
    ua: UA_ANDROID_13_PIXEL_CHROME_123_MOBILE,
    platformVersion: '13',
    browser: 'Chrome',
    browserVersion: '123.0.6312.86',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 13 Pixel 7 Pro Firefox 124',
    ua: UA_ANDROID_13_PIXEL_FIREFOX_124_MOBILE,
    platformVersion: '13',
    browser: 'Firefox',
    browserVersion: '124.0',
    deviceType: 'mobile',
    vendor: '',
  },
  {
    testName: 'Android 13 Pixel 7 Pro Edge 124',
    ua: UA_ANDROID_13_PIXEL_EDGE_124_MOBILE,
    platformVersion: '13',
    browser: 'Edge',
    browserVersion: '124.0.2478.52',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 13 Pixel 7 Opera 78',
    ua: UA_ANDROID_13_PIXEL_OPERA_78_MOBILE,
    platformVersion: '13',
    browser: 'Opera',
    browserVersion: '78.0.4095.147',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 13 Samsung S23 Samsung Internet 23',
    ua: UA_ANDROID_13_SAMSUNG_SI_23_MOBILE,
    platformVersion: '13',
    browser: 'Samsung Internet',
    browserVersion: '23.0',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 13 Oppo Find Chrome 124',
    ua: UA_ANDROID_13_OPPO_CHROME_124_MOBILE,
    platformVersion: '13',
    browser: 'Chrome',
    browserVersion: '124.0.6367.79',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 13 Pixel 7 Vivaldi 6.7',
    ua: UA_ANDROID_13_PIXEL_VIVALDI_6_7_MOBILE,
    platformVersion: '13',
    browser: 'Vivaldi',
    browserVersion: '6.7.3329.41',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 13 Pixel Fold Chrome 124',
    ua: UA_ANDROID_13_PIXEL_FOLD_CHROME_124,
    platformVersion: '13',
    browser: 'Chrome',
    browserVersion: '124.0.6367.79',
    deviceType: 'mobile',
    width: 600,
    height: 1230,
    pixelRatio: 3,
  },
  {
    testName: 'Android 13 Pixel Fold Edge 124',
    ua: UA_ANDROID_13_PIXEL_FOLD_EDGE_124,
    platformVersion: '13',
    browser: 'Edge',
    browserVersion: '124.0.2478.52',
    deviceType: 'mobile',
    width: 600,
    height: 1230,
  },
  {
    testName: 'Android 12 Pixel 6 Pro Chrome 120',
    ua: UA_ANDROID_12_PIXEL_CHROME_120_MOBILE,
    platformVersion: '12',
    browser: 'Chrome',
    browserVersion: '120.0.6099.199',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 12 Pixel 6 Firefox 119',
    ua: UA_ANDROID_12_PIXEL_FIREFOX_119_MOBILE,
    platformVersion: '12',
    browser: 'Firefox',
    browserVersion: '119.0',
    deviceType: 'mobile',
    vendor: '',
  },
  {
    testName: 'Android 12 Galaxy S21 Samsung Internet 20',
    ua: UA_ANDROID_12_SAMSUNG_SI_20_MOBILE,
    platformVersion: '12',
    browser: 'Samsung Internet',
    browserVersion: '20.0',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 12 Xiaomi Mi 11 Chrome 118',
    ua: UA_ANDROID_12_XIAOMI_MIUI_CHROME_118_MOBILE,
    platformVersion: '12',
    browser: 'Chrome',
    browserVersion: '118.0.5993.90',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 12 Pixel 6 WebView Chrome 120',
    ua: UA_ANDROID_12_PIXEL_WEBVIEW_120,
    platformVersion: '12',
    browser: 'Chrome',
    browserVersion: '120.0.6099.199',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 11 Pixel 5 Chrome 115',
    ua: UA_ANDROID_11_PIXEL_CHROME_115_MOBILE,
    platformVersion: '11',
    browser: 'Chrome',
    browserVersion: '115.0.5790.171',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 11 Pixel 5 Firefox 113',
    ua: UA_ANDROID_11_PIXEL_FIREFOX_113_MOBILE,
    platformVersion: '11',
    browser: 'Firefox',
    browserVersion: '113.0',
    deviceType: 'mobile',
    vendor: '',
  },
  {
    testName: 'Android 11 OnePlus 8T Edge 114',
    ua: UA_ANDROID_11_ONEPLUS_EDGE_114_MOBILE,
    platformVersion: '11',
    browser: 'Edge',
    browserVersion: '114.0.1823.86',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 11 Pixel 5 Opera 74',
    ua: UA_ANDROID_11_OPERA_74_MOBILE,
    platformVersion: '11',
    browser: 'Opera',
    browserVersion: '74.3.3922.71557',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 11 Galaxy S21 Samsung Internet 18',
    ua: UA_ANDROID_11_SAMSUNG_SI_18_MOBILE,
    platformVersion: '11',
    browser: 'Samsung Internet',
    browserVersion: '18.0',
    deviceType: 'mobile',
  },
  {
    testName: 'Android 14 Pixel Tablet Chrome 125',
    ua: UA_ANDROID_14_PIXEL_TABLET_CHROME_125,
    platformVersion: '14',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1280,
    height: 900,
    pixelRatio: 2,
  },
  {
    testName: 'Android 14 Pixel Tablet Firefox 125',
    ua: UA_ANDROID_14_PIXEL_TABLET_FIREFOX_125,
    platformVersion: '14',
    browser: 'Firefox',
    browserVersion: '125.0',
    deviceType: 'tablet',
    vendor: '',
    maxTouchPoints: 10,
    width: 1280,
    height: 900,
    pixelRatio: 2,
  },
  {
    testName: 'Android 14 Galaxy Tab S9 Samsung Internet 24',
    ua: UA_ANDROID_14_GALAXY_TAB_S9_SI_24,
    platformVersion: '14',
    browser: 'Samsung Internet',
    browserVersion: '24.0',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1280,
    height: 900,
    pixelRatio: 2,
  },
  {
    testName: 'Android 12 Galaxy Tab S8 Chrome 120',
    ua: UA_ANDROID_12_GALAXY_TAB_S8_CHROME_120,
    platformVersion: '12',
    browser: 'Chrome',
    browserVersion: '120.0.6099.199',
    deviceType: 'tablet',
    maxTouchPoints: 10,
    width: 1280,
    height: 900,
    pixelRatio: 2,
  },
  {
    testName: 'Android 10 Pixel 4 XL Chrome 96',
    ua: UA_ANDROID_10_PIXEL_CHROME_96_MOBILE,
    platformVersion: '10',
    browser: 'Chrome',
    browserVersion: '96.0.4664.104',
    deviceType: 'mobile',
    maxTouchPoints: 5,
    pixelRatio: 3,
  },
  {
    testName: 'Android 10 Pixel 4 Firefox 110',
    ua: UA_ANDROID_10_PIXEL_FIREFOX_110_MOBILE,
    platformVersion: '10',
    browser: 'Firefox',
    browserVersion: '110.0',
    deviceType: 'mobile',
    vendor: '',
  },
  {
    testName: 'Android 9 Galaxy S9 Samsung Internet 17',
    ua: UA_ANDROID_9_GALAXY_S9_SI_17_MOBILE,
    platformVersion: '9',
    browser: 'Samsung Internet',
    browserVersion: '17.0',
    deviceType: 'mobile',
    pixelRatio: 3,
  },
  {
    testName: 'Android 8 Huawei P20 Chrome 80',
    ua: UA_ANDROID_8_HUAWEI_P20_CHROME_80_MOBILE,
    platformVersion: '8.1.0',
    browser: 'Chrome',
    browserVersion: '80.0.3987.162',
    deviceType: 'mobile',
    pixelRatio: 2.5,
  },
  {
    testName: 'Android bot Googlebot smartphone',
    ua: UA_ANDROID_GOOGLEBOT_SMARTPHONE,
    platformVersion: '12',
    browser: 'Unknown',
    deviceType: 'bot',
    agentType: 'bot',
    vendor: '',
    maxTouchPoints: 0,
    hardwareConcurrency: 2,
    deviceMemory: 2,
    width: 412,
    height: 915,
    pixelRatio: 2,
  },
  {
    testName: 'Android WebView Facebook in-app browser',
    ua: UA_ANDROID_FACEBOOK_APP_WEBVIEW,
    platformVersion: '14',
    browser: 'Chrome',
    browserVersion: '125.0.6422.147',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
  {
    testName: 'Android WebView Twitter app',
    ua: UA_ANDROID_TWITTER_WEBVIEW,
    platformVersion: '13',
    browser: 'Chrome',
    browserVersion: '124.0.6367.79',
    deviceType: 'mobile',
    maxTouchPoints: 5,
  },
];
